ASSEMBLER=assembler
LINKER=linker
EMULATOR=emulator
TESTS=tests
COMMON=common

INDENT=" \ "

BIN_DIR = bin
SRC_DIR=src
INC_DIR=inc
OBJ_DIR=obj

CXX=g++
#CXXFLAGS= -I${INC_DIR} -std=c++20 -Wall -Wextra -pedantic -g
CXXFLAGS= -I${INC_DIR} -std=c++17

GCC=gcc
CFLAGS=-I${INC_DIR} -Wall -Wextra -O0

LD=gcc
LDFLAGS=-lm -lpthread

SHELL:=/bin/bash

FORCE: ;