ASSEMBLER=assembler
LINKER=linker
EMULATOR=emulator
TESTS=tests
COMMON=common

INDENT=" \ "

BIN_DIR = bin
SRC_DIR=src
INC_DIR=inc
OBJ_DIR=obj

CXX=g++
CXXFLAGS= -I${INC_DIR} -std=c++20
#CXXFLAGS= -I${INC_DIR} -std=c++20 -fsanitize=address

GCC=gcc
CFLAGS=-I${INC_DIR} -Wall -Wextra

LD=gcc
LDFLAGS=-lm

SHELL:=/bin/bash

FORCE: ;